### PR TITLE
add system status check

### PR DESCRIPTION
**Pull request by Splinter1984**
#214

### CODE REVIEW

**Review by fmrico — CHANGES_REQUESTED** [review]

**Review by fmrico — APPROVED** [review]

**Comment by Splinter1984** [comment]
was not as easy as expected

**Comment by fmrico** [comment]
Yes!! You can click on the details of the check that failed. If you analyze the log (it is better to see the raw logs) you will see that some linting tests didn't pass.

You could have detected this by running: `colcon test` after building, and looking in the logs of the failed packages :wink: 

 Thanks for your time!!

**Comment by fmrico** [comment]
Hi @Splinter1984 

Any advance on this PR? 

Best

**Comment by Splinter1984** [comment]
there was not much free time for it. 
i'll be back later

**Comment by Splinter1984** [comment]
Hi, @fmrico 
changes are complete, you can merge it into master

**Comment by fmrico** [comment]
LGTM!! Merging :rocket: 

Thanks @Splinter1984

**Pull request merged**
