### PR TITLE
Fix to have constants and numeric fluents in the goal

### LINKED ISSUE #261: Numeric fluents in the goal are not properly sent to problem expert
If in the terminal one select as goal a numeric fluent e.g. `set goal (and (needed agent) 0) (at agent l1))`, then the problem expert only receives (and (at agent l1)) ignoring the numerical part!

### PR DESCRIPTION
**Pull request by roveri-marco**
With this pull I fixed the possibility to have constants in the predicates/functions while setting them, and in the goal.

This will close #261

### CODE REVIEW

**Comment by fmrico** [comment]
Thanks for the PR @roveri-marco . I hope to have fixed the CI next week. Now it is failing for other reasons....

**Comment by fmrico** [comment]
CI seems to be fixed, but it is applying old pipeline. Can you rebase/merge?

**Comment by roveri-marco** [comment]
@fmrico I'm not able to understand why some tests fail. It seems the failure is not related to the changes. Can you help me in isolating the cause if this PR is the cause of the failure?

**Comment by fmrico** [comment]
Let me check...

**Comment by fmrico** [comment]
Hi @roveri-marco 

CI is passing now. I don't know if any tests are necessary to verify that this continues working after future changes. If you consider it necessary, please, open a new PR

Thanks!!! merging :rocket:

**Comment by roveri-marco** [comment]
If needed. I'll add a new PR. Thanks.

**Pull request merged**
