### PR TITLE
Fix goal structure issue 205

### PR DESCRIPTION
**Pull request by roveri-marco**
This PR allows for having complex goal structures (e.g. with and not) and will close issue #205

### CODE REVIEW

**Comment by fmrico** [comment]
Hi @roveri-marco 

Tests for many packages are failing, and the CI should be working properly now. May you check it?

Thanks!!

**Comment by roveri-marco** [comment]
@fmrico sure I'll do. Which ROS version shall I use? The latest?

**Comment by fmrico** [comment]
ROS2 Humble, please

**Comment by roveri-marco** [comment]
@fmrico still under revision

**Comment by roveri-marco** [comment]
On my PC with a docker image I get the following behavior
```
root@676fa7809d47:/home/marco/plansys2-ws# colcon build
Starting >>> plansys2_msgs
Starting >>> plansys2_lifecycle_manager
Finished <<< plansys2_lifecycle_manager [0.95s]
Finished <<< plansys2_msgs [3.94s]
Starting >>> plansys2_pddl_parser
Finished <<< plansys2_pddl_parser [1.13s]
Starting >>> plansys2_core
Finished <<< plansys2_core [1.06s]
Starting >>> plansys2_popf_plan_solver
Starting >>> plansys2_tfd_plan_solver
Finished <<< plansys2_popf_plan_solver [1.26s]
Starting >>> plansys2_domain_expert
Finished <<< plansys2_tfd_plan_solver [1.28s]
Finished <<< plansys2_domain_expert [1.78s]
Starting >>> plansys2_problem_expert
Finished <<< plansys2_problem_expert [2.87s]
Starting >>> plansys2_planner
Starting >>> plansys2_tools
Finished <<< plansys2_tools [3.28s]
Finished <<< plansys2_planner [6.47s]
Starting >>> plansys2_executor
[Processing: plansys2_executor]
Finished <<< plansys2_executor [34.0s]
Starting >>> plansys2_bringup
Starting >>> plansys2_terminal
Starting >>> plansys2_bt_actions
Starting >>> plansys2_tests
Finished <<< plansys2_bt_actions [11.9s]
Finished <<< plansys2_bringup [15.2s]
Finished <<< plansys2_tests [16.1s]
Finished <<< plansys2_terminal [24.6s]
Starting >>> plansys2_bt_example
Starting >>> plansys2_cascade_example
Starting >>> plansys2_multidomain_example
Starting >>> plansys2_patrol_navigation_example
Starting >>> plansys2_simple_example
Finished <<< plansys2_simple_example [7.74s]
Finished <<< plansys2_cascade_example [8.29s]
Finished <<< plansys2_multidomain_example [8.80s]
Finished <<< plansys2_patrol_navigation_example [26.8s]
[Processing: plansys2_bt_example]
Finished <<< plansys2_bt_example [1min 20s]

Summary: 20 packages finished [2min 37s]
root@676fa7809d47:/home/marco/plansys2-ws#
```

**Comment by roveri-marco** [comment]
@fmrico can you help me to understand what's going wrong? It seems the ```terminal_test``` fails, but when I run it in my docker configured with humble ROS2 it works perfectly. See the log above. Might it be a problem of timeout?

**Pull request merged**
